-- radar-infra/database/init/01_radar_schema.sql

-- PostgreSQL 17.x compatible schema for `radar` database

-- Connect to the specific database before creating schemas
\connect radar

-- Securities
CREATE TABLE IF NOT EXISTS public.securities
(
    id            integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    symbol        character varying(10)  NOT NULL UNIQUE,
    description   character varying(100) NOT NULL,
    store_locally boolean DEFAULT false  NOT NULL
);
COMMENT ON TABLE public.securities IS 'Marketable financial instruments';
COMMENT ON COLUMN public.securities.id IS 'Internal unique identifier';
COMMENT ON COLUMN public.securities.symbol IS 'Acronym identifier of the financial instrument';
COMMENT ON COLUMN public.securities.description IS 'Description of the financial instrument';
COMMENT ON COLUMN public.securities.store_locally IS 'Flag indicating whether prices obtained from the cloud should be saved in the database';

INSERT INTO public.securities (id, symbol, description, store_locally) OVERRIDING SYSTEM VALUE
VALUES (1, 'SPX', 'S&P 500 Index', true),
       (2, 'NDQ', 'NASDAQ 100 Index', true),
       (3, 'GOLD', 'Gold USD', false),
       (10, 'SPY', 'SPDR S&P 500 ETF Trust', false),
       (11, 'QQQ', 'Invesco QQQ Trust', false),
       (12, 'SOXX', 'iShares Semiconductor ETF', false),
       (13, 'XBI', 'SPDR S&P Biotech ETF', false),
       (14, 'AIQ', 'Global X Artificial Intelligence & Technology ETF', false),
       (15, 'TQQQ', 'ProShares UltraPro QQQ', false),
       (16, 'TECL', 'Direxion Daily Technology Bull 3X Shares', false),
       (17, 'SOXL', 'Direxion Daily Semiconductor Bull 3X Shares', false),
       (18, 'AIBU', 'Direxion Daily AI And Big Data Bull 2X Shares', false),
       (19, 'SPXL', 'Direxion Daily S&P500 Bull 3X Shares', false),
       (20, 'UBOT', 'Direxion Daily Robotics, Artificial Intelligence & Automation Index Bull 2X Shares', false),
       (21, 'SQQQ', 'ProShares UltraPro Short QQQ', false),
       (22, 'SOXS', 'Direxion Daily Semiconductor Bear 3X Shares', false),
       (23, 'AIBD', 'Direxion Daily AI And Big Data Bear 2X Shares', false),
       (24, 'SPXS', 'Direxion Daily S&P 500 Bear 3X Shares', false),
       (25, 'LABU', 'Direxion Daily S&P Biotech Bull 3X Shares', false),
       (26, 'LABD', 'Direxion Daily S&P Biotech Bear 3X Shares', false),
       (27, 'IWM', 'iShares Russell 2000 ETF', false),
       (28, 'TNA', 'Direxion Daily Small Cap Bull 3X Shares', false),
       (29, 'TZA', 'Direxion Daily Small Cap Bear 3X Shares', false),
       (30, 'AAPL', 'Apple Inc.', false),
       (31, 'AMZN', 'Amazon.com, Inc.', false),
       (32, 'AVGO', 'Broadcom Inc.', false),
       (33, 'GOOGL', 'Alphabet Inc.', false),
       (34, 'META', 'Meta Platforms, Inc.', false),
       (35, 'MSFT', 'Microsoft Corporation', false),
       (36, 'NFLX', 'Netflix, Inc.', false),
       (37, 'NVDA', 'NVIDIA Corporation', false),
       (38, 'TSLA', 'Tesla, Inc.', false),
       (39, 'ADBE', 'Adobe Inc.', false),
       (40, 'BABA', 'Alibaba Group Holding Limited', false),
       (41, 'MELI', 'MercadoLibre, Inc.', false),
       (42, 'ORCL', 'Oracle Corporation', false),
       (43, 'BTC-USD', 'Bitcoin USD', false),
       (44, 'BITX', '2x Bitcoin Strategy ETF', false),
       (45, 'IBIT', 'iShares Bitcoin Trust ETF', false),
       (46, 'WGMI', 'Valkyrie Bitcoin Miners ETF', false),
       (47, 'XLF', 'State Street Financial Select Sector SPDR ETF', false),
       (48, 'FAS', 'Direxion Daily Financial Bull 3X Shares', false),
       (49, 'FAZ', 'Direxion Daily Financial Bear 3X Shares', false),
       (50, 'FXI', 'iShares China Large-Cap ETF', false),
       (51, 'YINN', 'Direxion Daily FTSE China Bull 3X Shares', false),
       (52, 'EEM', 'iShares MSCI Emerging Markets ETF', false),
       (53, 'EDC', 'Direxion Daily MSCI Emerging Markets Bull 3X Shares', false),
       (54, 'EDZ', 'Direxion Daily MSCI Emerging Markets Bear 3X Shares', false),
       (55, 'VGK', 'Vanguard FTSE Europe ETF', false),
       (56, 'GDX', 'VanEck Gold Miners ETF', false),
       (57, 'NUGT', 'Direxion Daily Gold Miners Index Bull 2X Shares', false),
       (58, 'DUST', 'Direxion Daily Gold Miners Index Bear 2X Shares', false);

SELECT setval('public.securities_id_seq', COALESCE(MAX(id), 0) + 1, false)
FROM public.securities;

-- Strategies
CREATE TABLE IF NOT EXISTS public.strategies
(
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       character varying(50) NOT NULL,
    acronym    character varying(25) NOT NULL UNIQUE,
    pool       character varying(10) DEFAULT '' NOT NULL,
    unit_label character varying(5)  DEFAULT '' NOT NULL
);
COMMENT ON TABLE public.strategies IS 'Speculation/investment strategies on financial instruments';
COMMENT ON COLUMN public.strategies.id IS 'Internal unique identifier';
COMMENT ON COLUMN public.strategies.name IS 'Name, caption';
COMMENT ON COLUMN public.strategies.acronym IS 'Acronym';
COMMENT ON COLUMN public.strategies.pool IS 'Group of strategies';
COMMENT ON COLUMN public.strategies.unit_label IS 'Unit of measurement for the strategy inputs, for example: $ for SMA';

INSERT INTO public.strategies (id, name, acronym, pool, unit_label)
VALUES (1, 'Simple Moving Average', 'SMA', 'MA', '$'),
       (2, 'Roller Coaster over RSI(14)', 'RSI(14) RC', 'RSI', ''),
       (3, 'Simple Moving Average over RSI(14)', 'RSI(14) SMA', 'RSI', ''),
       (4, 'Two Bands over RSI(14)', 'RSI(14) 2B', 'RSI', '');

SELECT setval('public.strategies_id_seq', COALESCE(MAX(id), 0) + 1, false)
FROM public.strategies;

-- Daily Data
CREATE TABLE IF NOT EXISTS public.daily_data
(
    id             integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    security_id    integer        NOT NULL REFERENCES public.securities (id),
    date           date           NOT NULL,
    open           numeric(13, 4) NOT NULL,
    high           numeric(13, 4) NOT NULL,
    low            numeric(13, 4) NOT NULL,
    close          numeric(13, 4) NOT NULL,
    volume         bigint         NOT NULL,
    percent_change numeric(8, 2),
    UNIQUE (security_id, date)
);
COMMENT ON TABLE public.daily_data IS 'Daily prices (OHLC) for the securities storable in the database';
COMMENT ON COLUMN public.daily_data.id IS 'Internal unique identifier';
COMMENT ON COLUMN public.daily_data.security_id IS 'Reference to the security (instrument) the data belongs to';
COMMENT ON COLUMN public.daily_data.date IS 'The date of the price data';
COMMENT ON COLUMN public.daily_data.open IS 'The opening price of the security on that date';
COMMENT ON COLUMN public.daily_data.high IS 'The highest price reached during the day';
COMMENT ON COLUMN public.daily_data.low IS 'The lowest price reached during the day';
COMMENT ON COLUMN public.daily_data.close IS 'The closing price of the security on that date';
COMMENT ON COLUMN public.daily_data.volume IS 'The number of shares or contracts traded';
COMMENT ON COLUMN public.daily_data.percent_change IS 'The percentage price change from the previous day';

SELECT setval('public.daily_data_id_seq', COALESCE(MAX(id), 0) + 1, false)
FROM public.daily_data;

-- Ratios
CREATE TABLE IF NOT EXISTS public.ratios
(
    id                            integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    symbol                        character varying(10) NOT NULL,
    strategy_id                   integer               NOT NULL REFERENCES public.strategies (id),
    timeframe                     smallint              NOT NULL,
    inputs                        character varying(50) NOT NULL,
    is_long_position              boolean               NOT NULL,
    is_in_process                 boolean DEFAULT false NOT NULL,
    from_date                     date                  NOT NULL,
    to_date                       date                  NOT NULL,
    initial_price                 numeric(12, 2)        NOT NULL,
    final_price                   numeric(9, 2)         NOT NULL,
    net_change                    real                  NOT NULL,
    signals                       smallint              NOT NULL,
    winnings                      real                  NOT NULL,
    losses                        real                  NOT NULL,
    net_profit                    real                  NOT NULL,
    expected_value                real                  NOT NULL,
    win_probability               real                  NOT NULL,
    loss_probability              real                  NOT NULL,
    average_win                   real                  NOT NULL,
    average_loss                  real                  NOT NULL,
    min_percentage_change_to_win  numeric(6, 2)         NOT NULL,
    max_percentage_change_to_win  numeric(6, 2)         NOT NULL,
    total_sessions                smallint              NOT NULL,
    winning_sessions              smallint              NOT NULL,
    losing_sessions               smallint              NOT NULL,
    percentage_exposure           real                  NOT NULL,
    first_input_date              date                  NOT NULL,
    last_input_date               date                  NOT NULL,
    last_output_date              date,
    last_input_price              numeric(12, 2),
    last_output_price             numeric(12, 2),
    last_stop_loss                numeric(12, 2),
    UNIQUE (symbol, strategy_id, inputs, timeframe, is_long_position)
);
COMMENT ON TABLE public.ratios IS 'ratios to evaluate the performance of speculation/investment strategies';
COMMENT ON COLUMN public.ratios.id IS 'Internal unique identifier';
COMMENT ON COLUMN public.ratios.symbol IS 'Acronym identifier of financial instrument';
COMMENT ON COLUMN public.ratios.timeframe IS 'Time frames: 1.Intraday, 2.Daily, 3.Weekly, 4.Monthly';
COMMENT ON COLUMN public.ratios.inputs IS 'Defines the independent variables of the strategy, for example for a moving average it is the length in sessions of the period for calculating the average';
COMMENT ON COLUMN public.ratios.is_long_position IS 'Defines whether the ratio relates to a long or short market position';
COMMENT ON COLUMN public.ratios.is_in_process IS 'Flag indicating whether the record can be deleted during any running process';
COMMENT ON COLUMN public.ratios.from_date IS 'Indicates the date from which the strategy was tested to identify results and ratios';
COMMENT ON COLUMN public.ratios.to_date IS 'Indicates the date up to which the strategy was tested to identify results and ratios.';
COMMENT ON COLUMN public.ratios.initial_price IS 'Initial price of the period in which the strategy was tested';
COMMENT ON COLUMN public.ratios.final_price IS 'Final price of the period in which the strategy was tested';
COMMENT ON COLUMN public.ratios.net_change IS 'Percentage change of the final price over the initial price';
COMMENT ON COLUMN public.ratios.signals IS 'Number of trade signals identified by the strategy';
COMMENT ON COLUMN public.ratios.winnings IS 'Total gain on positive/winning operations';
COMMENT ON COLUMN public.ratios.losses IS 'Total loss on negative/losing operations.';
COMMENT ON COLUMN public.ratios.net_profit IS 'Percentage of net profit got following the input and output signals. Formula: (winnings_ - losses_) / initial_price';
COMMENT ON COLUMN public.ratios.expected_value IS 'Mathematical expectation of the strategy. Formula: (win_probability * average_win) + (loss_probability * average_loss).';
COMMENT ON COLUMN public.ratios.win_probability IS 'Percentage of positive/winning operations';
COMMENT ON COLUMN public.ratios.loss_probability IS 'Percentage of negative/losing operations';
COMMENT ON COLUMN public.ratios.average_win IS 'Average profit of the positive/winning operations';
COMMENT ON COLUMN public.ratios.average_loss IS 'Average loss of the negative/losing operations';
COMMENT ON COLUMN public.ratios.min_percentage_change_to_win IS 'Minimum percentage change of input sessions for the positive/winning operations';
COMMENT ON COLUMN public.ratios.max_percentage_change_to_win IS 'Maximum percentage change of input sessions for the positive/winning operations';
COMMENT ON COLUMN public.ratios.total_sessions IS 'Total number of sessions to which the strategy has been evaluated';
COMMENT ON COLUMN public.ratios.winning_sessions IS 'Number of sessions spent/elapsed during positive/winning operations';
COMMENT ON COLUMN public.ratios.losing_sessions IS 'Number of sessions spent/elapsed during negative/losing operations';
COMMENT ON COLUMN public.ratios.percentage_exposure IS 'Percentage time during which the strategy was active. Formula: (winning_sessions + losing_sessions) / total_sessions';
COMMENT ON COLUMN public.ratios.first_input_date IS 'Date of the first input signal';
COMMENT ON COLUMN public.ratios.last_input_date IS 'Date of the last input signal';
COMMENT ON COLUMN public.ratios.last_output_date IS 'Date of the last output signal';
COMMENT ON COLUMN public.ratios.last_input_price IS 'Input price for the last position opened by the tested strategy';
COMMENT ON COLUMN public.ratios.last_output_price IS 'Output price for the last position opened by the tested strategy';
COMMENT ON COLUMN public.ratios.last_stop_loss IS 'Stop loss for the last position opened by the tested strategy';

SELECT setval('public.ratios_id_seq', COALESCE(MAX(id), 0) + 1, false)
FROM public.ratios;

-- Synonyms
CREATE TABLE IF NOT EXISTS public.synonyms
(
    id          integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    provider_id integer               NOT NULL,
    security_id integer               NOT NULL REFERENCES public.securities (id),
    ticker      character varying(10) NOT NULL,
    UNIQUE (provider_id, security_id)
);
COMMENT ON TABLE public.synonyms IS 'Synonyms of security symbols in different quote providers.
The providerId column is managed without a master table, and its values are:
1 -> Yahoo';
COMMENT ON COLUMN public.synonyms.id IS 'Internal unique identifier';
COMMENT ON COLUMN public.synonyms.provider_id IS 'Quote provider identifier';
COMMENT ON COLUMN public.synonyms.security_id IS 'Security identifier';
COMMENT ON COLUMN public.synonyms.ticker IS 'Symbol ticker por the quote provider';

INSERT INTO public.synonyms (id, provider_id, security_id, ticker) OVERRIDING SYSTEM VALUE
VALUES (1, 1, 1, '^GSPC'),
       (2, 1, 2, '^NDX'),
       (3, 1, 3, 'GC=F');

SELECT setval('public.synonyms_id_seq', COALESCE(MAX(id), 0) + 1, false)
FROM public.synonyms;
