# settings.yml
symbols:
  - 'BTC-USD'
  - 'GOLD'
  - 'IWM'
  - 'QQQ'
  - 'SOXX'
  - 'SPY'
  - 'XBI'
  - 'XLE'
  - 'XLF'
shortables:
  - 'BTC-USD'
  - 'GOLD'
  - 'IWM'
  - 'QQQ'
  - 'SOXX'
  - 'SPY'
  - 'XBI'
  - 'XLE'
  - 'XLF'
evaluable_strategies:  # Use attribute name in `class Strategies`, module `evaluable_strategies.py`
  - sma       # Profitable SMA
  - rsi_sma   # Profitable RSI(14) SMA
  - rsi_rc    # Profitable RSI(14) RC
  - rsi_2b    # Profitable RSI(14) 2B