# settings.yml

# Reserved symbols retained during database cleanup.
# settings.py combines this list with symbols.
done:

symbols:
  - 'SPY'     # Most important
  - 'QQQ'
  - 'RSP'
  - 'SOXX'
  - 'XBI'
  - 'GDX'
  - 'IWM'
  - 'VTI'     # Total US stock market
  - 'VFLO'    # Cashflow-focused
  - 'TQQQ'    # 2x3x ETFs
  - 'TECL'
  - 'SOXL'
  - 'LABU'
  - 'SPXL'
  - 'NUGT'
  - 'TNA'
  - 'SQQQ'
  - 'TECS'
  - 'SOXS'
  - 'LABD'
  - 'SPXS'
  - 'TZA'
  - 'DUST'
  - 'ROM'     # Technology 2x long ~ TECL
  - 'REW'     # Technology 2x inverse ~ TECS
  - 'USD'     # Semiconductors 2x long
  - 'SSG'     # Semiconductors 2x inverse
  - 'MAGS'    # Magnificent
  - 'MAGX'    # 2x Long
  - 'DRAM'    # Memory ETF
  - 'XLI'     # Industrials
  - 'UXI'     # 2x long
  - 'SIJ'     # 2x inverse
  - 'DUSL'    # 3x long
  - 'BTC-USD' # Bitcoin
  - 'BITX'    # 2x long
  - 'SBIT'    # 2x inverse
  - 'WGMI'    # Bitcoin Miners
  - 'DBC'     # Commodities
  - 'PDBC'    # Commodities
  - 'GOLD'    # Gold
  - 'GLD'     # Gold ETF
  - 'UGL'     # 2x long
  - 'GLL'     # 2x inverse
  - 'SILVER'  # Silver
  - 'SLV'     # Silver ETF
  - 'AGQ'     # 2x long
  - 'ZSL'     # 2x inverse
  - 'XLE'     # Energy
  - 'ERX'     # 2x long
  - 'ERY'     # 2x inverse
  - 'USOIL'   # Oil
  - 'USO'     # Oil ETF
  - 'UNG'     # Natural Gas ETF
  - 'XLF'     # Financials
  - 'FAS'     # 2x long
  - 'FAZ'     # 2x inverse
  - 'REET'    # REIT - Real Estate Investment Trust
  - 'FXI'     # China
  - 'YINN'    # 3x long
  - 'EWH'     # Hong Kong
  - 'EEM'     # Emerging
  - 'EDC'     # 3x long
  - 'EDZ'     # 3x inverse
  - 'VGK'     # Europe
  - 'AAPL'    # Individual stocks
  - 'ADBE'
  - 'AMAT'
  - 'AMD'
  - 'AMZN'
  - 'AVGO'
  - 'BABA'
  - 'COST'
  - 'GOOGL'
  - 'INTC'
  - 'JPM'
  - 'LRCX'
  - 'MA'
  - 'MELI'
  - 'META'
  - 'MSFT'
  - 'MU'
  - 'NFLX'
  - 'NVDA'
  - 'ONON'
  - 'ORCL'
  - 'PLTR'
  - 'TSLA'
  - 'TSM'
  - 'V'
  - 'WMT'
  - 'DIA'     # Down Jones
  - 'UDOW'    # 3x long
  - 'SDOW'    # 3x inverse
  - 'TLT'     # Treasury bonds ETF
  - 'TMF'     # 3x long
  - 'TTT'     # 3x inverse
  - 'SVXY'    # Short-volatility
  - 'UVXY'    # Long-volatility leveraged

evaluable_strategies: # Use attribute name of the `class Strategies`, module `evaluable_strategies.py`
  - sma       # Profitable SMA
  - rsi_sma   # Profitable RSI(14) SMA
  - rsi_rc    # Profitable RSI(14) RC
  - rsi_2b    # Profitable RSI(14) 2B

rsi_input_filter: 'price_action'  # options: 'none', 'price_action', 'atr_volatility', 'sma_trend'

win_probability_threshold: 0.5  # Minimum winning probability threshold for a strategy to be persisted into the database

stop_loss_cap_daily: 0.12  # Maximum percentage loss threshold for daily timeframe
stop_loss_cap_weekly: 0.18  # Maximum percentage loss threshold for weekly timeframe
