# docker/docker-compose.core.yml
# Hybrid Core service: attached to both host and external Docker networks to allow switching the PostgreSQL target via .env configuration.

services:
  # --- Unattended analysis core service ---
  core:
    build:
      context: ..                             # Service directory relative to this file
      dockerfile: docker/Dockerfile
    image: radar-core:dev-0.5.0
    container_name: radar-core
    restart: 'no'                             # It will either run manually or remain paused after execution
    shm_size: '2gb'                           # CRITICAL for HPC/Polars: Increase shared memory size
    env_file:
      - ../envs/.env.core                     # Unversioned file .env with secure credentials, its path is relative to this docker-compose.yml
    # Required to connect from the container to a PostgreSQL hosted on Windows
    extra_hosts:
      - "host.docker.internal:host-gateway"   # Maps host.docker.internal to the host IP
    # Required to connect from this container to an external PostgreSQL container
    networks:
      - radar-network                         # Shared network for inter-service communication
    # Resource limits - a similar concept used in K8S
    # deploy:
    #    resources:
    #      limits:
    #        cpus: '2.00'                        # Limit to % of one CPU core
    #        memory: 2056M                       # Limit to MB RAM
    #      reservations:
    #        cpus: '0.50'                        # Reserve % of one CPU core
    #        memory: 1024M                       # Reserve MB RAM

# Network configuration for service communication
networks:
  # Shared external network to communicate with the PostgreSQL container from project `radar-infra` (see `docker-compose.dev.yml`)
  radar-network:                              # Network name
    external: true                            # Use an existing network created outside of this `compose` file (e.g.`docker network create radar-network`)
